# Generated by Django 5.0.6 on 2024-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
