# Generated by Django 5.0.6 on 2024-06-21 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0010_emailrecord_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='client',
            field=models.ForeignKey(help_text='The client associated with this email record.', on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='emails_app.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='error_message',
            field=models.TextField(blank=True, help_text='The error message if the email sending failed.', null=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='recipient',
            field=models.EmailField(help_text='The email address of the recipient.', max_length=254, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='status',
            field=models.CharField(help_text="The status of the email (e.g., 'Sent', 'Failed').", max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='subject',
            field=models.CharField(help_text='The subject of the email.', max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='task_type',
            field=models.CharField(choices=[('single', 'Single Email'), ('bulk', 'Bulk Email')], default='single', help_text='The type of task used to send the email (single or bulk).', max_length=20, verbose_name='Task Type'),
        ),
        migrations.AlterField(
            model_name='emailrecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the email record was created.', verbose_name='Timestamp'),
        ),
    ]
