# Generated by Django 5.0.6 on 2024-06-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_key',
            field=models.CharField(editable=False, help_text='Unique API key for client', max_length=100, unique=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='client',
            name='static_ip',
            field=models.GenericIPAddressField(help_text='Static IP address of the client system', unique=True, verbose_name='Static IP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(editable=False, max_length=255, verbose_name='Access Token'),
        ),
    ]
