# Generated by Django 5.0.6 on 2024-06-17 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0004_alter_client_api_key_alter_client_static_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='api_key',
            field=models.CharField(blank=True, editable=False, help_text='Unique API key for client', max_length=100, null=True, unique=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='client',
            name='token_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiration date and time of the access token', null=True, verbose_name='Token Expiry'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
    ]
