# Generated by Django 5.0.6 on 2024-06-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0006_remove_client_api_key_remove_client_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrecord',
            options={'verbose_name': 'Email Record', 'verbose_name_plural': 'Email Records'},
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='emails_app.client', verbose_name='Client'),
        ),
    ]
