# Generated by Django 5.0.6 on 2024-06-20 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0007_alter_emailrecord_options_emailrecord_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecord',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='email_records', to='emails_app.client', verbose_name='Client'),
            preserve_default=False,
        ),
    ]
