# Generated by Django 5.0.6 on 2024-06-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0008_alter_emailrecord_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text="The SMTP server address. For example, 'smtp.gmail.com'.", max_length=255, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(help_text='The port to use for the SMTP server. Common ports are 587 for TLS or 465 for SSL.', verbose_name='SMTP Port')),
                ('username', models.CharField(help_text='The username for authenticating with the SMTP server.', max_length=255, verbose_name='SMTP Username')),
                ('password', models.CharField(help_text='The password for authenticating with the SMTP server. Ensure this is stored securely.', max_length=255, verbose_name='SMTP Password')),
                ('use_tls', models.BooleanField(default=True, help_text='Whether to use TLS (Transport Layer Security) when connecting to the SMTP server.', verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, help_text='Whether to use SSL (Secure Sockets Layer) when connecting to the SMTP server. Note: Do not enable both TLS and SSL.', verbose_name='Use SSL')),
                ('default_from_email', models.EmailField(help_text="The default email address to use for the 'From' field when sending emails.", max_length=254, verbose_name='Default From Email')),
            ],
            options={
                'verbose_name': 'SMTP Setting',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
    ]
