# Generated by Django 5.0.6 on 2024-06-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails_app', '0009_smtpsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailrecord',
            name='task_type',
            field=models.CharField(choices=[('single', 'Single Email'), ('bulk', 'Bulk Email')], default='single', max_length=20),
        ),
    ]
